language: node_js
  - 10
script:
  - ng build --prod
notifications:
  email:
    on_failure: change
    on_success: change

deploy:
  - provider: firebase
    token:
      secure: QOiOPJmnl2kwmsa2G0j+yK7cyVNcNKBJNYEKEJajZqFHhn7bipH1UlVydKDfWVbDUohblFOj6JeGcxoiFdAD9b404fUrNG6DtGAdsBOrIgQ/UA8YGGf+T+MwZPfjdgyrXLSX3cnLtDoEFVcSjhwP9Ze/xiGDiISMGlfciYzMJwbkUlz0qAs6Zpps2Y/xKeAeD5TeviGX03X4AoGQwnaSIjFoB99eGDJJ6StvLcYk3bhR6FDAzJvqNtOhi5DRKxwmYSddoaDwTMWel3CIS9mP08SMGkMfb+T3sW33r/P1NJEWaxkXkY4QTnB2DHydEc8uEIQH/NUh1egNy/LIwgAc4ijx8v4Dh/pD+shoQpRQ6elZGEihfBifx9kR7GqSYtKhbjkxqdUsLIZ+Vv7ifJReZqBM3dZaA1AAWgTedWRkeiv9a1WQH3QPIUM1aikwillG9KgytDAJl2f+tWiFiCh6N20BpGR9QW3K8fq+R0sUcNJoHirOFjFpCo7JZVT8ET54zBQEaSOGrG2EWqX1EiG0Rwny7fqQ44kTIgjsqX4Qtt9830V/KGl6cp0Vyy+osOjwT0HsHGUcGH800fF4r+YvYWNgJxOotWwq3WKxuNjgkd2B34mqrVFa4QuaoMWO3hbYPuxpb4J30h2YCggBk7KpAE7YIOCCAf3y+LVo2Vqpibg=
    project: post-visualize-development
    on:
      branch: dev
  - provider: firebase
    token:
      secure: QOiOPJmnl2kwmsa2G0j+yK7cyVNcNKBJNYEKEJajZqFHhn7bipH1UlVydKDfWVbDUohblFOj6JeGcxoiFdAD9b404fUrNG6DtGAdsBOrIgQ/UA8YGGf+T+MwZPfjdgyrXLSX3cnLtDoEFVcSjhwP9Ze/xiGDiISMGlfciYzMJwbkUlz0qAs6Zpps2Y/xKeAeD5TeviGX03X4AoGQwnaSIjFoB99eGDJJ6StvLcYk3bhR6FDAzJvqNtOhi5DRKxwmYSddoaDwTMWel3CIS9mP08SMGkMfb+T3sW33r/P1NJEWaxkXkY4QTnB2DHydEc8uEIQH/NUh1egNy/LIwgAc4ijx8v4Dh/pD+shoQpRQ6elZGEihfBifx9kR7GqSYtKhbjkxqdUsLIZ+Vv7ifJReZqBM3dZaA1AAWgTedWRkeiv9a1WQH3QPIUM1aikwillG9KgytDAJl2f+tWiFiCh6N20BpGR9QW3K8fq+R0sUcNJoHirOFjFpCo7JZVT8ET54zBQEaSOGrG2EWqX1EiG0Rwny7fqQ44kTIgjsqX4Qtt9830V/KGl6cp0Vyy+osOjwT0HsHGUcGH800fF4r+YvYWNgJxOotWwq3WKxuNjgkd2B34mqrVFa4QuaoMWO3hbYPuxpb4J30h2YCggBk7KpAE7YIOCCAf3y+LVo2Vqpibg=
    project: post-visualize
    on:
      branch: master
